---
# This playbook provisions an environment to start experimenting with Ansible on AWS

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Remove Created Machines
      ec2:
        region: "{{ aws_region }}"
        state: absent
        instance_ids: "{{ remove_instance_ids }}"
      when: remove_instance_ids is defined 

    - name: Create EC2 Environment Loop
      include: "create_ec2_env.yml dev=Dev{{ item }}"
      loop: "{{ query('sequence', 'start=1 end=1') }}"
      when: remove_instance_ids is undefined

- hosts: linux
  gather_facts: no
  vars:
    ansible_port: 22
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ keypair }}.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Health Check Linux Machines
      wait_for_connection:
      when: remove_instance_ids is undefined

- hosts: windows
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986
    ansible_user: Administrator
    ansible_password: "{{ ansible_password }}"
  tasks:
    - name: Health Check Windows Machines
      wait_for_connection:
      when: remove_instance_ids is undefined
